name: First Workflow
on: [push]

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - name: simple js action
        id: greet # we need an id in order to get an output
        uses: actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b
        # commit id
        with: 
          who-to-greet: Aris # this is the input 
      - name: log greeting time
        run: echo "{{ steps.greet.output.time }}"